# Generated by Django 3.2.7 on 2021-09-20 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id_bco', models.AutoField(primary_key=True, serialize=False)),
                ('nom_bco', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'banco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_bol', models.AutoField(primary_key=True, serialize=False)),
                ('nro_boleta', models.IntegerField(unique=True)),
                ('fec_emision', models.DateField()),
                ('id_res_atencion', models.IntegerField()),
                ('tiene_propina', models.CharField(max_length=1)),
                ('tiene_dcto', models.CharField(max_length=1)),
                ('valor_dcto', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'boleta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('fec_hora_apertura', models.DateField()),
                ('fec_hora_cierre', models.DateField()),
                ('monto_apertura', models.IntegerField()),
            ],
            options={
                'db_table': 'caja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaInsumo',
            fields=[
                ('id_cat_ins', models.AutoField(primary_key=True, serialize=False)),
                ('nom_categoria', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categoria_insumo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id_cat_prod', models.AutoField(primary_key=True, serialize=False)),
                ('desc_cat_prod', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categoria_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('rut_cli', models.IntegerField()),
                ('dv', models.CharField(max_length=1)),
                ('nom_cli', models.CharField(max_length=50)),
                ('ap_pat_cli', models.CharField(max_length=100)),
                ('ap_mat_cli', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(max_length=16)),
                ('correo', models.CharField(max_length=100)),
                ('fec_nac', models.DateField()),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id_comanda', models.AutoField(primary_key=True, serialize=False)),
                ('fec_hora_ingreso', models.DateField()),
                ('fec_hora_egreso', models.DateField()),
            ],
            options={
                'db_table': 'comanda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_com', models.AutoField(primary_key=True, serialize=False)),
                ('nom_com', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuadraturaCaja',
            fields=[
                ('id_cuadr', models.AutoField(primary_key=True, serialize=False)),
                ('fec_cuadratura', models.DateField()),
                ('monto_cuadrado', models.IntegerField()),
                ('tuvo_descuadre', models.CharField(max_length=1)),
                ('monto_descuadre', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cuadratura_caja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('nro_cta', models.BigIntegerField()),
                ('nro_chip', models.BigIntegerField(blank=True, null=True)),
                ('fec_expiracion', models.DateField()),
                ('saldo_disp', models.IntegerField()),
                ('sobregiro', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cuenta_bancaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleBoleta',
            fields=[
                ('id_det_bol', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=255)),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_boleta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id_det_fact', models.AutoField(primary_key=True, serialize=False)),
                ('total_neto', models.IntegerField()),
                ('iva', models.FloatField()),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleMenu',
            fields=[
                ('id_det_menu', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'detalle_menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleOc',
            fields=[
                ('id_det_oc', models.AutoField(primary_key=True, serialize=False)),
                ('neto_det', models.IntegerField()),
                ('iva', models.FloatField()),
                ('total_unit', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_oc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id_det_orden', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_orden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetPed',
            fields=[
                ('id_det_ped', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('medida', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'det_ped',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetResAt',
            fields=[
                ('id_det_res_at', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'det_res_at',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_dir', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=255)),
                ('numeracion', models.IntegerField()),
                ('nro_casa_depto', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'direccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id_disp', models.AutoField(primary_key=True, serialize=False)),
                ('fec_disponible', models.DateField()),
                ('hora_disponible', models.CharField(max_length=5)),
                ('cant_persona', models.IntegerField()),
            ],
            options={
                'db_table': 'disponibilidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoFactura',
            fields=[
                ('id_est_fact', models.AutoField(primary_key=True, serialize=False)),
                ('desc_est_fact', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estado_factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoMenu',
            fields=[
                ('id_est_menu', models.AutoField(primary_key=True, serialize=False)),
                ('desc_est_menu', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estado_menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoMesa',
            fields=[
                ('id_est_mesa', models.AutoField(primary_key=True, serialize=False)),
                ('desc_est_mesa', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estado_mesa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoResAt',
            fields=[
                ('id_est_res', models.AutoField(primary_key=True, serialize=False)),
                ('desc_est_res_at', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estado_res_at',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoReserva',
            fields=[
                ('id_est_rsv', models.AutoField(primary_key=True, serialize=False)),
                ('desc_est_rsv', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estado_reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoUsuario',
            fields=[
                ('id_est_usr', models.AutoField(primary_key=True, serialize=False)),
                ('desc_est_usr', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'estado_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstCaja',
            fields=[
                ('id_est_caja', models.AutoField(primary_key=True, serialize=False)),
                ('desc_est_caja', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'est_caja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstComanda',
            fields=[
                ('id_est_cmd', models.AutoField(primary_key=True, serialize=False)),
                ('desc_est_cmd', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'est_comanda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstDisponibilidad',
            fields=[
                ('id_est_disp', models.AutoField(primary_key=True, serialize=False)),
                ('desc_est_disp', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'est_disponibilidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstFormaPago',
            fields=[
                ('id_est_forma_pago', models.AutoField(primary_key=True, serialize=False)),
                ('desc_est_forma_pago', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'est_forma_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstInsumo',
            fields=[
                ('id_est_ins', models.AutoField(primary_key=True, serialize=False)),
                ('desc_est_ins', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'est_insumo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstOc',
            fields=[
                ('id_est_oc', models.AutoField(primary_key=True, serialize=False)),
                ('desc_est_oc', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'est_oc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstOrden',
            fields=[
                ('id_est_orden', models.AutoField(primary_key=True, serialize=False)),
                ('desc_est_orden', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'est_orden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstPedido',
            fields=[
                ('id_est_ped', models.AutoField(primary_key=True, serialize=False)),
                ('desc_est_ped', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'est_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstReceta',
            fields=[
                ('id_est_rec', models.AutoField(primary_key=True, serialize=False)),
                ('desc_est_rec', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'est_receta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('nro_factura', models.IntegerField(unique=True)),
                ('fec_emision', models.DateField()),
                ('fec_pago', models.DateField(blank=True, null=True)),
                ('total_neto', models.IntegerField()),
                ('iva', models.FloatField()),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id_form_pago', models.AutoField(primary_key=True, serialize=False)),
                ('desc_form_pago', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'forma_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GiroProveedor',
            fields=[
                ('id_giro_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('desc_giro', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'giro_proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id_ingrediente', models.AutoField(primary_key=True, serialize=False)),
                ('nom_ingrediente', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ingrediente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id_ins', models.AutoField(primary_key=True, serialize=False)),
                ('nom_insumo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'insumo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarioInsumo',
            fields=[
                ('id_inv_ins', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
                ('fec_vencimiento', models.DateField()),
            ],
            options={
                'db_table': 'inventario_insumo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogError',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('cod_error', models.CharField(max_length=255)),
                ('desc_error', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'log_error',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarcaInsumo',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nom_marca', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'marca_insumo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_menu', models.AutoField(primary_key=True, serialize=False)),
                ('nro_menu', models.IntegerField()),
                ('nombre_menu', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id_mesa', models.AutoField(primary_key=True, serialize=False)),
                ('nro_mesa', models.IntegerField()),
                ('cant_sillas', models.IntegerField()),
            ],
            options={
                'db_table': 'mesa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MotivoDescuadre',
            fields=[
                ('id_motivo', models.AutoField(primary_key=True, serialize=False)),
                ('desc_mot', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'motivo_descuadre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MotivoRetiro',
            fields=[
                ('id_motivo', models.AutoField(primary_key=True, serialize=False)),
                ('desc_motivo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'motivo_retiro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NroCaja',
            fields=[
                ('id_no_caja', models.AutoField(primary_key=True, serialize=False)),
                ('nro_caja', models.IntegerField()),
                ('fec_creacion', models.DateField()),
            ],
            options={
                'db_table': 'nro_caja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NvlAccPerfil',
            fields=[
                ('id_nvl', models.AutoField(primary_key=True, serialize=False)),
                ('desc_nvl', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'nvl_acc_perfil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenComida',
            fields=[
                ('id_ord_com', models.AutoField(primary_key=True, serialize=False)),
                ('fec_hora_inicio', models.DateField()),
                ('fec_hora_termino', models.DateField()),
                ('personas', models.IntegerField()),
            ],
            options={
                'db_table': 'orden_comida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id_oc', models.AutoField(primary_key=True, serialize=False)),
                ('nro_oc', models.CharField(max_length=100)),
                ('total_neto_oc', models.IntegerField()),
                ('iva', models.FloatField()),
                ('total_oc', models.IntegerField()),
                ('fec_oc', models.DateField()),
                ('dias_vigencia', models.IntegerField()),
            ],
            options={
                'db_table': 'orden_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_ped', models.AutoField(primary_key=True, serialize=False)),
                ('nro_pedido', models.IntegerField()),
                ('fec_ped', models.DateField()),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('desc_perfil', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'perfil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('desc_permiso', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'permiso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PorcDcto',
            fields=[
                ('id_porc_dcto', models.AutoField(primary_key=True, serialize=False)),
                ('porc_dcto', models.FloatField()),
            ],
            options={
                'db_table': 'porc_dcto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PorcPropina',
            fields=[
                ('id_porc_prop', models.AutoField(primary_key=True, serialize=False)),
                ('porc_prop', models.FloatField()),
            ],
            options={
                'db_table': 'porc_propina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('rut_prv', models.IntegerField(unique=True)),
                ('dv_prv', models.CharField(max_length=1)),
                ('razon_social', models.CharField(max_length=255)),
                ('nom_corto_prv', models.CharField(max_length=255)),
                ('tlfn_prv', models.CharField(max_length=16)),
                ('correo_prv', models.CharField(max_length=4000)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_receta', models.AutoField(primary_key=True, serialize=False)),
                ('nom_receta', models.CharField(max_length=100)),
                ('tiempo_prep', models.IntegerField()),
                ('temp_ideal', models.IntegerField()),
                ('instrucciones', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'receta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_reg', models.AutoField(primary_key=True, serialize=False)),
                ('nom_reg', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fec_reserva', models.DateField()),
                ('fecha_hora_reserva', models.DateField()),
                ('cant_asistentes', models.IntegerField()),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResumenAtencion',
            fields=[
                ('id_res_at', models.AutoField(primary_key=True, serialize=False)),
                ('total_at', models.IntegerField()),
                ('fec_hora_at', models.DateField()),
            ],
            options={
                'db_table': 'resumen_atencion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RetiroCaja',
            fields=[
                ('id_retiro', models.AutoField(primary_key=True, serialize=False)),
                ('fec_hora_retiro', models.DateField()),
            ],
            options={
                'db_table': 'retiro_caja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id_tipo_cta', models.AutoField(primary_key=True, serialize=False)),
                ('desc_tipo_cta', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_cuenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDireccion',
            fields=[
                ('id_tipo_dir', models.AutoField(primary_key=True, serialize=False)),
                ('desc_tipo_dir', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_direccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoInsumo',
            fields=[
                ('id_tipo_ins', models.AutoField(primary_key=True, serialize=False)),
                ('desc_tipo_ins', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tipo_insumo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tip_prod', models.AutoField(primary_key=True, serialize=False)),
                ('desc_tipo_prod', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoTransaccion',
            fields=[
                ('id_tipo_trans', models.AutoField(primary_key=True, serialize=False)),
                ('desc_trans', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_transaccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransaccionBancaria',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('fec_transaccion', models.DateField()),
                ('monto_transaccion', models.IntegerField()),
            ],
            options={
                'db_table': 'transaccion_bancaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('desc_ubicacion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ubicacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id_un_med', models.AutoField(primary_key=True, serialize=False)),
                ('desc_un_med', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'unidad_medida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usr', models.AutoField(primary_key=True, serialize=False)),
                ('contrasenia', models.CharField(max_length=128)),
                ('last_login', models.DateField()),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateField()),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fec_venta', models.DateField()),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DireccionCliente',
            fields=[
                ('id_dir', models.OneToOneField(db_column='id_dir', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.direccion')),
            ],
            options={
                'db_table': 'direccion_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DireccionProveedor',
            fields=[
                ('id_proveedor', models.OneToOneField(db_column='id_proveedor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.proveedor')),
            ],
            options={
                'db_table': 'direccion_proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecetaIngrediente',
            fields=[
                ('id_receta', models.OneToOneField(db_column='id_receta', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.receta')),
                ('cant_ingrediente', models.IntegerField()),
            ],
            options={
                'db_table': 'receta_ingrediente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RevisionCaja',
            fields=[
                ('id_caja', models.OneToOneField(db_column='id_caja', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.caja')),
            ],
            options={
                'db_table': 'revision_caja',
                'managed': False,
            },
        ),
    ]
